apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: lab-cluster
  region: us-east-1

nodeGroups:
  - name: nodes-general
    labels:
        role: workers
    instanceType: t3.medium
    desiredCapacity: 1
    volumeSize: 20
