apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lab-app
  template:
    metadata:
      labels:
        app: lab-app
    spec:
      containers:
        - name: lab-app
          image: isaackumi/alabi-lab:$TAG
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: DB_LOCAL_URI
              value: mongodb://mongo:27017/lab
      restartPolicy: Always