apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab-app
  template:
    metadata:
      labels:
        app: lab-app
    spec:
      containers:
        - name: lab-app
          image: isaackumi/alabi-lab:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: DB_LOCAL_URI
              valueFrom:
                configMapKeyRef:
                  key: database_url
                  name: mongodb-configmap
             
      restartPolicy: Always