apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: lab-service
spec:
  selector:
    app: lab-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer