name: Docker Build and Scan

on:
  workflow_dispatch:
  push:
   branches:
     - master
   

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
<<<<<<< HEAD
        run: docker build -t isaackumi/alabi-lab:latest . 
=======
        run: docker build -t isaackumi/alabi-lab:latest . -f Dockerfile
>>>>>>> 3c356e39d74a68cc736af2d2ff5cc7d5fe057f50

      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.43.0/trivy_0.43.0_Linux-64bit.tar.gz
          tar zxvf trivy_0.43.0_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/

      - name: Scan Docker Image with Trivy
<<<<<<< HEAD
        run: trivy image --severity HIGH --no-progress isaackumi/alabi-lab:latest
=======
        run: trivy image --severity HIGH --no-progress isaackumi/alabi-lab-demo:latest
>>>>>>> 3c356e39d74a68cc736af2d2ff5cc7d5fe057f50

  push:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.21.3'
        id: install

      - name: Automatic Tagging of Releases
        uses: rymndhng/release-on-push-action@master
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        with:
          tag_prefix: ""
          bump_version_scheme: patch
          release_body: "The official release for isaackumi/alabi-lab"

      - name: Check Release Output Parameters
        run: |
          echo "Got tag name ${{ steps.release.outputs.tag_name }}"
          echo "Got release version ${{ steps.release.outputs.version }}"

      - name: Build Docker Image
<<<<<<< HEAD
        run: docker build -t isaackumi/alabi-lab:${{ steps.release.outputs.version }} . 
=======
        run: docker build -t isaackumi/alabi-lab:${{ steps.release.outputs.version }} . -f Dockerfile
>>>>>>> 3c356e39d74a68cc736af2d2ff5cc7d5fe057f50

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image to Docker Hub
<<<<<<< HEAD
        run: docker push isaackumi/alabi-lab:${{ steps.release.outputs.version }}

      - name: Update kube config
        if:  failure()
        run: aws eks update-kubeconfig --name lab-cluster --region us-east-1
=======
        run: docker push isaackumi/alabi-lab:${{ steps.release.outputs.version }}
>>>>>>> 3c356e39d74a68cc736af2d2ff5cc7d5fe057f50
